name: "go-install-action"
description: "Install a go package"
inputs:
  package:
    description: go package to install
    required: true
  version:
    description: version of go package to install
  modfile:
    description: path to go.mod file defining the package's version
  output:
    description: name of the built binary
  output-path-env:
    description: environment variable containing the output path
outputs:
  path:
    description: Path to the installed package binary
    value: ${{ steps.install.outputs.path }}

runs:
  using: "composite"
  steps:
  - name: install ${{ inputs.package }}
    id: install
    run: |
      set -euo pipefail

      package="${{ inputs.package }}"
      version="${{ inputs.version }}"
      modfile="${{ inputs.modfile }}"
      output="${{ inputs.output }}"
      output_path_env="${{ inputs.output-path-env }}"
      
      gobin="$(go env GOBIN)"
      gopath="$(go env GOPATH)"

      work_dir="${RUNNER_TEMP}/reconcilerio/go-install-action"
      mkdir -p "${work_dir}"

      cmd=""
      if [[ "${modfile}" != "" ]] ; then
        cmd="${cmd:+${cmd} }-modfile ${modfile}"
      fi
      cmd="${cmd:+${cmd} }${package}"
      if [[ "${version}" != "" ]] ; then
        cmd="${cmd}@${version}"
      fi

      echo "##[group]go install ${cmd}"
        GOBIN="${work_dir}" go install ${cmd}
      echo "##[endgroup]"

      bin="$(ls -1 "${work_dir}")"
      output="${output:-${bin}}"
      output_dir="${gobin:-${gopath}/bin}"
      mkdir -p "${output_dir}"
      path="${output_dir}/${output}"
      mv "${work_dir}/${bin}" "${path}"

      echo "installed to: ${path}"
      echo "path=${path}" >> "${GITHUB_OUTPUT}"
      if [[ "${output_path_env}" != "" ]] ; then
        echo "${output_path_env}=${path}" >> "${GITHUB_ENV}"
      fi
      rm -rf "${work_dir}"
    shell: bash
