name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
    tags:
    - '**'
  pull_request: {}

jobs:
  test:
    name: Test go-install action
    strategy: &tests
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-24.04
          version: latest
          toolchain: auto
        - os: ubuntu-24.04-arm
          version: latest
          toolchain: auto
        - version: "v0.20.0" # git tag
        - version: "d36047ae385302d20acd872e28f036a475fb9417" # git commit
          cache-enabled: 'true'
        - working-directory: hack/crane
          cache-enabled: true
        - version: latest
          output-path-env: CRANE
          cache-enabled: 'false'
        - package: sigs.k8s.io/kind
          version: latest
          output: kind-latest
          output-dir: /usr/local/bin
          output-path-env: KIND
          cache-enabled: false
          test-args: --version
        - tool: crane
          working-directory: hack/tools
        - tool: github.com/google/go-containerregistry/cmd/crane
          working-directory: hack/tools
        - package: sigs.k8s.io/kind
          version: latest
          download-url-template: https://github.com/kubernetes-sigs/kind/releases/download/${version}/kind-${os}-${arch}
          expect-provenance: download
        - package: github.com/google/go-containerregistry/cmd/crane
          version: v0.21.7
          download-url-template: https://github.com/google/go-containerregistry/releases/download/${version}/go-containerregistry_${os^}_${arch/amd64/x86_64}.tar.gz
          download-path-within-archive: crane
          expect-provenance: download
        - package: github.com/golangci/golangci-lint/v2/cmd/golangci-lint
          version: latest
          download-url-template: https://github.com/golangci/golangci-lint/releases/download/${version}/golangci-lint-${version:1}-${os}-${arch}.tar.gz
          download-path-within-archive: golangci-lint-${version:1}-${os}-${arch}/golangci-lint
          expect-provenance: download
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v7
      with:
        go-version-file: hack/crane/go.mod
        cache-dependency-path: '**/go.sum'
    - name: Install package
      id: install
      uses: ./
      with: &with-install
        package: ${{ matrix.package || case(!matrix.package && !matrix.tool, 'github.com/google/go-containerregistry/cmd/crane', '') }}
        version: ${{ matrix.version }}
        tool: ${{ matrix.tool }}
        working-directory: ${{ matrix.working-directory }}
        toolchain: ${{ matrix.toolchain }}
        download-url-template: ${{ matrix.download-url-template }}
        download-path-within-archive: ${{ matrix.download-path-within-archive }}
        output: ${{ matrix.output }}
        output-dir: ${{ matrix.output-dir }}
        output-path-env: ${{ matrix.output-path-env }}
        cache-enabled: ${{ matrix.cache-enabled }}
    - name: Debug
      run: |
        set -euo pipefail

        tree "${RUNNER_TEMP}/reconcilerio/go-install-action"
        ls -la "${{ steps.install.outputs.path }}"
    - name: Test install
      run: ${{ steps.install.outputs.path }} ${{ matrix.test-args || 'version' }}
    - name: Test install env
      if: matrix.output-path-env
      run: ${${{ matrix.output-path-env }}} ${{ matrix.test-args || 'version' }}
  test-from-cache:
    name: Test go-install action (from cache)
    needs: test
    strategy: *tests
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v7
      with:
        go-version-file: hack/crane/go.mod
    - name: Install package
      id: install
      uses: ./
      with: *with-install
    - name: Debug
      run: |
        set -euo pipefail

        tree "${RUNNER_TEMP}/reconcilerio/go-install-action"
        ls -la "${{ steps.install.outputs.path }}"
    - name: Test install
      run: ${{ steps.install.outputs.path }} ${{ matrix.test-args || 'version' }}
    # test artifact provenance on the second job, as the first job seeds the cache
    - name: Test provenance
      run: |
        set -euo pipefail

        expect_provenance="${{ matrix.expect-provenance }}"
        if [[ "${expect_provenance}" == "" ]] ; then
          cache_enabled="${{ matrix.cache-enabled }}"
          if [[ "${cache_enabled:-true}" == "true" ]] ; then
            expect_provenance=cache
          else
            expect_provenance=source
          fi
        fi

        provenance="${{ steps.install.outputs.provenance }}"
        echo "artifact-provenance = ${provenance}"

        if [[ "${expect_provenance}" != "${provenance}" ]] ; then
          echo "::error title=Expected provenance::artifact from ${provenance}, expected to be from ${expect_provenance}"
          exit 1
        fi
